name: env_burned_area_3
channels:
  - terradue
  - conda-forge
  - defaults
dependencies:
  - python=3.5
  - requests
  - cioppy
  - snap
  - ipykernel
  - otb
  - gdal>2.2.2
  - poppler<0.66
  - lxml
  - shapely
